### ISSUE TITLE
How to use rancher ?

### ISSUE THREAD

**Issue by garceri** [kallqvist/rundeck-rancher#15]
I set the CATTLE_URL ACCESS_KEY and SECRET_KEY variables as well as the environment id which was set at the project config
When i try to run a simple run-once container task i'm getting:

```
16:20:58			Traceback (most recent call last):
16:20:58			File "/var/lib/rundeck/libext/cache/rancher/container-runonce.py", line 11, in <module>
16:20:58			from _containers_shared import *
16:20:58			File "/var/lib/rundeck/libext/cache/rancher/_containers_shared.py", line 113, in <module>
16:20:58			raise Exception("Can't run, environment ID is not set!")
16:20:58			Exception: Can't run, environment ID is not set!
16:20:58			[rancher-trigger-runonce]: result code: 1
16:20:58			Failed: NonZeroResultCode: Script result code was: 1
```

What am i doing wrong ?

**Comment by kallqvist** [comment]
Just to clarify, you did set the environment id in the project config where you can select the "Rancher container resource collector" as a node source like in this image?

![screen shot 2017-07-13 at 22 34 46](https://user-images.githubusercontent.com/937404/28186708-775b3fb2-681c-11e7-877e-dfe75fafdda5.png)

That and to ensure that "dispatch to nodes" is selected in the job config is the only thing you should have to do.

This error can only happen when the environment variable is shows up in the plugin as an empty string and as far as I know missing any of these two configs should be the only way that could happen.

**Comment by garceri** [comment]
Yep, this is the relevant part of project config file:
```
resources.source.2.config.environment_id=1a95
resources.source.2.config.limit_one_container=true
resources.source.2.type=rancher-resources
```

**Comment by kallqvist** [comment]
Do you get the same error when searching for containers on the nodes page as well?

**Comment by garceri** [comment]
I resolved this. it was a Layer-8 Error ;-)

**Comment by kallqvist** [comment]
haha, nice :)
just let me know if anything else would show up, good luck!
