### ISSUE TITLE
Command Execution in Rancher

### ISSUE THREAD

**Issue by garceri** [kallqvist/rundeck-rancher#16]
Maybe i'm not reading it right, but the documentation says to disable tty in Rancher config, does it means that:
a) the Rundeck container has to have the  ``` tty: false``` flag set in its compose file
b) The container where you want to execute commands needs ```tty: false```
c) You are talking about a Rancher config option that i have not been able to find.

I've tried both A and B and i keep getting an exception about 
``` raise Exception("Can't run, TTY must be disabled in rancher settings")```

**Comment by kallqvist** [comment]
It's about answer b, the service in rancher must have TTY disabled for the log output to be separated into stdout and stderr.

The plugin is using this so it can detect any kind of error messages happening during the script execution in the container and mark it as a failed job in rundeck
