### ISSUE TITLE
Output stops at error

### ISSUE THREAD

**Issue by gevert** [kallqvist/rundeck-rancher#7]
Whenever a job fails the log from the output stops. Would be great if I could see what happens in the job after the output to stderr if the script continues.

**Comment by kallqvist** [comment]
This is also being targeted as part of https://github.com/kallqvist/rundeck-rancher/issues/4

**Comment by kallqvist** [comment]
Should be fixed as of 37ca61112f46e76de2c77cb3e8f45e7089914b4f
