### ISSUE TITLE
BusyBox/Alpine date gives Failed to read log

### ISSUE THREAD

**Issue by gevert** [kallqvist/rundeck-rancher#8]
The default BusyBox/Alpine version of date does not have support for nanoseconds which will break the script due to incorrect timestamp. 

Installing the coreutils package in Alpine with pkg resolved the problem for me.

**Comment by kallqvist** [comment]
The nanosecond precision is now removed from the log format as of 37ca61112f46e76de2c77cb3e8f45e7089914b4f.
Please try again and reopen if issues remain.
