### ISSUE TITLE
Regex error on lines with missing timestamp

### ISSUE THREAD

**Issue by gevert** [kallqvist/rundeck-rancher#9]
`2016-12-18 12:14:43 INFO Server:379 - Started @2028ms
2016-12-1
[ E ] PARSE_ERROR: 8 12:14:44 INFO ContextHandler:744 - Started o.s.j.s.ServletContextHandler@46419dac{/metrics/json,null,AVAILABLE}
 ::
Traceback (most recent call last):
File "/var/lib/rundeck/libext/cache/rancher/node-executor.py", line 269, in <module>
raise Exception(log_handler.last_error)
Exception: error from callback <function logs_on_message at 0x7fde55fd4b18>: Failed to read log format, regex does not match!
Failed: NonZeroResultCode: [rancher-executor] Result code: 1`

**Comment by kallqvist** [comment]
There are some regex improvements in 10f4b95bbac7d23525f5ad90fd06bab9b74e453d and a2b354eb329914a628809c82d009e82ad88f8c55.
Can you try again?

**Comment by kallqvist** [comment]
There have been issues with rancher websockets sometimes delivering half lines of text.
Some added logic around that have been attempted as part of 37ca61112f46e76de2c77cb3e8f45e7089914b4f.

Closing this for now, please re-open if issues remain.
